title: Microservicio de analíticas
description: Documentación del microservicio que gestiona las analíticas y métricas de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/microservicio-analiticas"
